basePath: /
definitions:
  Event:
    properties:
      ip:
        example: 127.0.0.1
        type: string
      login:
        example: login
        type: string
      password:
        example: password
        type: string
    type: object
  JSONError:
    properties:
      code:
        type: string
      description:
        type: string
      message:
        type: string
    type: object
  JSONResponse:
    properties:
      ok:
        type: boolean
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: api.anti-bruteforce.local
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Anti Bruteforce
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Anti Bruteforce API
  version: "0.1"
paths:
  /auth:
    post:
      consumes:
      - application/json
      description: Попытка авторизации
      parameters:
      - description: Создание события
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/Event'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/JSONResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/JSONError'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/JSONResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/JSONError'
      summary: Попытка авторизации
      tags:
      - Auth
  /ping:
    get:
      description: Пинг-Понг
      responses:
        "200":
          description: OK
      summary: Пинг-Понг
      tags:
      - Test
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
