basePath: /
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: api.anti-bruteforce.local
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Anti Bruteforce
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Anti Bruteforce API
  version: "0.1"
paths: {}
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
