basePath: /
definitions:
  JSONError:
    properties:
      code:
        type: string
      description:
        type: string
      message:
        type: string
    type: object
  JSONResponse:
    properties:
      ok:
        type: boolean
    type: object
  RequestCheck:
    properties:
      ip:
        example: 127.0.0.1
        type: string
      login:
        example: login
        type: string
      password:
        example: password
        type: string
    type: object
  RequestDeleteBucket:
    properties:
      ip:
        example: 127.0.0.1
        type: string
      login:
        example: login
        type: string
    type: object
  RequestIP:
    properties:
      net:
        example: 127.0.0.0/24
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: api.anti-bruteforce.local
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Anti Bruteforce
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Anti Bruteforce API
  version: "0.1"
paths:
  /add/black-list:
    post:
      consumes:
      - application/json
      description: Добавить сеть в черный список
      parameters:
      - description: Добавить сеть в черный список
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/RequestIP'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/JSONError'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/JSONError'
      summary: Добавить сеть в черный список
      tags:
      - Add
  /add/white-list:
    post:
      consumes:
      - application/json
      description: Добавить сеть в белый список
      parameters:
      - description: Добавить сеть в белый список
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/RequestIP'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/JSONError'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/JSONError'
      summary: Добавить сеть в белый список
      tags:
      - Add
  /check/auth:
    post:
      consumes:
      - application/json
      description: Попытка авторизации
      parameters:
      - description: Создание события
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/RequestCheck'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/JSONResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/JSONError'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/JSONResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/JSONError'
      summary: Попытка авторизации
      tags:
      - Check
  /delete/black-list:
    post:
      consumes:
      - application/json
      description: Удалить сеть из черного списка
      parameters:
      - description: Удалить сеть из черного списка
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/RequestIP'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/JSONError'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/JSONError'
      summary: Удалить сеть из черного списка
      tags:
      - Delete
  /delete/bucket:
    post:
      consumes:
      - application/json
      description: Удалить бакет
      parameters:
      - description: Удалить бакет
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/RequestDeleteBucket'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/JSONError'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/JSONError'
      summary: Удалить бакет
      tags:
      - Delete
  /delete/white-list:
    post:
      consumes:
      - application/json
      description: Удалить сеть из белого списка
      parameters:
      - description: Удалить сеть из белого списка
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/RequestIP'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/JSONError'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/JSONError'
      summary: Удалить сеть из белого списка
      tags:
      - Delete
  /ping:
    get:
      description: Пинг-Понг
      responses:
        "200":
          description: OK
      summary: Пинг-Понг
      tags:
      - Test
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
