app:

logger:
  level : debug # info / debug / warning / error
http:
  host: 0.0.0.0
  port: 80
limits:
  login:
    maxPerMinute: 5
    refillRateIsSecond: 1
    cleanupInterval: 120s
    ttl: 120s
broker:
  ampq: "amqp://admin:admin@amqp:5672"
  queue:
    notify: "calendar_notify"