app:
  overlapping: false # разрешается перекрытие даты
logger:
  level : debug # info / debug / warning / error
http:
  host: 0.0.0.0
  port: 80
broker:
  ampq: "amqp://admin:admin@amqp:5672"
  queue:
    notify: "calendar_notify"