app:

storage:
  type: sqlproxy # sql / memory / sqlproxy
  dsn: "postgres://postgres:postgres@postgres:5432/anti_bruteforce"
logger:
  level : debug # info / debug / warning / error
http:
  host: 0.0.0.0
  port: 80
limits:
  login:
    maxPerMinute: 100
    refillRateInSecond: 0.1
    cleanupInterval: 120s
    ttl: 120s
  password:
    maxPerMinute: 10
    refillRateInSecond: 0.1
    cleanupInterval: 120s
    ttl: 12s
  ip:
    maxPerMinute: 1
    refillRateInSecond: 0.1
    cleanupInterval: 120s
    ttl: 12s