name: Anti bruteforce tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  GO111MODULE: "on"
  GOLANG_VERSION: ~1.24
  GOLANGCI_LINT_VERSION: v2.7.2
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: Check out code
        uses: actions/checkout@v4

      - name: Linters
        uses: golangci/golangci-lint-action@v7
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: Check out code
        uses: actions/checkout@v4

      - name: Unit tests
        run: CGO_ENABLED=1 go test -race -count 100 ./...
        working-directory: .

  tests_by_makefile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: Check out code
        uses: actions/checkout@v4

      - name: make lint
        run: make lint
        working-directory: .

      - name: make build
        run: make build
        working-directory: .

      - name: make test
        run: make test
        working-directory: .
